### PR TITLE
update templates for Jenkins master and slave to match

### PR DESCRIPTION
**Pull request by ssegalredhat**
https://github.com/CentOS-PaaS-SIG/contra-env-setup/pull/118

### CODE REVIEW

**Review by arilivigni — COMMENTED** [review]
@joejstuart and I were discussing this and we think leaving the existing s2i template alone and having a separate directory with jinja2 templates for ansible makes the most sense.
This way folks can still use the existing templates if they want to load them directly into OpenShift without using the contra-env-setup.

Something like jenkins leave the s2i directory as is
under jenkins/master/jinja2-templates

I don't know how many of these we would have besides Jenkins to run in the same namespace???

**Comment by ssegalredhat** [comment]
@arilivigni in jenkins/master directory there is only 1 template. Same in jenkins/slave. contra-env-setup is configured to look inside specific folder and pickup all templates there. So if you want leave original templates, we need create another main folder for master and slave and whichever template you want leave at original.
If we leave original templates in some place, and we merge current PR, then contra-env-setup will be unable to process original templates anyway. If this is ok, and old templates needed only for the record in some folder, then we can do it. But if you want still be able to process old templates, then you suggest to cancel the whole initiative?

**Comment by joejstuart** [comment]
Sasha, I think if you don’t mind moving the templates you created to master/jinja2-templates and slave/jinja2-templates that will satisfy the requirements.

**Comment by joejstuart** [comment]
@ssegalredhat if you don't mind placing the templates here. https://github.com/CentOS-PaaS-SIG/contra-env-setup/tree/master/playbooks/roles/os_temps/templates.
@arilivigni and I spoke can you make the changes to the contra-env-setup [PR118](https://github.com/CentOS-PaaS-SIG/contra-env-setup/pull/118) based on moving the templates to [contra-env-setup/playbooks/roles/os_temps/templates](https://github.com/CentOS-PaaS-SIG/contra-env-setup/tree/master/playbooks/roles/os_temps/templates) . Thank you.

This also will be easier since it is just in the contra-env-setup and you can abandon this PR

**Pull request closed without merging**
