### PR TITLE
fix refs

### PR DESCRIPTION
**Pull request by skatlapa**
pr doesn't get recognized in Git Lab, changing to mr

### CODE REVIEW

**Comment by skatlapa** [comment]
https://github.com/CentOS-PaaS-SIG/contra-env-infra/issues/41

**Comment by joejstuart** [comment]
I don't know if this is the fix since it's referring to a github repo. I think the fix is to only have one ref spec entry in Jenkins.

**Comment by joejstuart** [comment]
Updating "refspec" in the json to an array and then updating the data type in the init script should fix it. I haven't tested it though.

https://github.com/CentOS-PaaS-SIG/contra-env-infra/blob/master/jenkins/master/openshift/configuration/init.groovy.d/contra-global_variables.groovy#54

**Comment by joejstuart** [comment]
This isn't needed anymore so closing

**Pull request closed without merging**
